/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Jobcard: typeof import('./src/components/Jobcard.vue')['default']
    Jobdetail: typeof import('./src/components/Jobdetail.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    Positionpick: typeof import('./src/components/Positionpick.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
